"""empty message

Revision ID: 158115263cb5
Revises: 5c1a09488932
Create Date: 2018-10-01 22:19:52.475363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158115263cb5'
down_revision = '5c1a09488932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_boxscore_punt_returns',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.drop_table('nfl_punt_returns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_punt_returns',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_punt_returns_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_punt_returns_pkey')
    )
    op.drop_table('nfl_boxscore_punt_returns')
    # ### end Alembic commands ###
