"""empty message

Revision ID: 2236be5f3ade
Revises: bcf2045c4e06
Create Date: 2018-10-28 11:16:54.832140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2236be5f3ade'
down_revision = 'bcf2045c4e06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espn_projections')
    op.drop_table('shark_projections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shark_projections',
    sa.Column('segment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scoring', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('player_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], name='shark_projections_team_id_fkey')
    )
    op.create_table('espn_projections',
    sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('points', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('positions', postgresql.ARRAY(sa.VARCHAR(length=8)), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], name='espn_projections_team_id_fkey')
    )
    # ### end Alembic commands ###
