"""empty message

Revision ID: 2a8ecdf28f51
Revises: c9b90d46957e
Create Date: 2018-10-01 19:36:01.953637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a8ecdf28f51'
down_revision = 'c9b90d46957e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_boxscore_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=32), nullable=True),
    sa.Column('away_team', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfl_boxscore_defense',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('t', sa.Integer(), nullable=True),
    sa.Column('a', sa.Integer(), nullable=True),
    sa.Column('sck', sa.Float(), nullable=True),
    sa.Column('int', sa.Integer(), nullable=True),
    sa.Column('ff', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_fumbles',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('fum', sa.Integer(), nullable=True),
    sa.Column('lost', sa.Integer(), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('yds', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_kicking',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('fg_att', sa.Integer(), nullable=True),
    sa.Column('fg_made', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('xp_att', sa.Integer(), nullable=True),
    sa.Column('xp_made', sa.Integer(), nullable=True),
    sa.Column('pts', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_kickoff_returns',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_passing',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('cp', sa.Integer(), nullable=True),
    sa.Column('at', sa.Integer(), nullable=True),
    sa.Column('yds', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('int', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_punting',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('i20', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_receiving',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('rec', sa.Integer(), nullable=True),
    sa.Column('yds', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_boxscore_rushing',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('att', sa.Integer(), nullable=True),
    sa.Column('yds', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    op.create_table('nfl_punt_returns',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=32), nullable=True),
    sa.Column('no', sa.Integer(), nullable=True),
    sa.Column('avg', sa.Integer(), nullable=True),
    sa.Column('td', sa.Integer(), nullable=True),
    sa.Column('lg', sa.Integer(), nullable=True),
    sa.Column('team', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_punt_returns')
    op.drop_table('nfl_boxscore_rushing')
    op.drop_table('nfl_boxscore_receiving')
    op.drop_table('nfl_boxscore_punting')
    op.drop_table('nfl_boxscore_passing')
    op.drop_table('nfl_boxscore_kickoff_returns')
    op.drop_table('nfl_boxscore_kicking')
    op.drop_table('nfl_boxscore_fumbles')
    op.drop_table('nfl_boxscore_defense')
    op.drop_table('nfl_boxscore_game')
    # ### end Alembic commands ###
