"""empty message

Revision ID: 2b16e6ef1da2
Revises: 42fd2e9153a0
Create Date: 2018-10-14 18:22:33.614467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b16e6ef1da2'
down_revision = '42fd2e9153a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_game',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('detail_id', sa.String(length=64), nullable=True),
    sa.Column('season_value', sa.Integer(), nullable=True),
    sa.Column('season_type', sa.String(length=32), nullable=True),
    sa.Column('week_order', sa.Integer(), nullable=True),
    sa.Column('week_value', sa.Integer(), nullable=True),
    sa.Column('week_type', sa.String(length=32), nullable=True),
    sa.Column('home_team_id', sa.String(length=64), nullable=True),
    sa.Column('away_team_id', sa.String(length=64), nullable=True),
    sa.Column('home_team_abbr', sa.String(length=32), nullable=True),
    sa.Column('away_team_abbr', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfl_player_game_stats',
    sa.Column('game_id', sa.String(length=64), nullable=False),
    sa.Column('team_abbr', sa.String(length=32), nullable=True),
    sa.Column('person_name', sa.String(length=128), nullable=True),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('defensive_assists', sa.Float(), nullable=True),
    sa.Column('defensive_interceptions', sa.Float(), nullable=True),
    sa.Column('defensive_interceptions_yards', sa.Float(), nullable=True),
    sa.Column('defensive_forced_fumble', sa.Float(), nullable=True),
    sa.Column('defensive_passes_defensed', sa.Float(), nullable=True),
    sa.Column('defensive_sacks', sa.Float(), nullable=True),
    sa.Column('defensive_safeties', sa.Float(), nullable=True),
    sa.Column('defensive_solo_tackles', sa.Float(), nullable=True),
    sa.Column('defensive_total_tackles', sa.Float(), nullable=True),
    sa.Column('defensive_tackles_for_a_loss', sa.Float(), nullable=True),
    sa.Column('touchdowns_defense', sa.Float(), nullable=True),
    sa.Column('fumbles_lost', sa.Float(), nullable=True),
    sa.Column('fumbles_total', sa.Float(), nullable=True),
    sa.Column('kick_returns', sa.Float(), nullable=True),
    sa.Column('kick_returns_long', sa.Float(), nullable=True),
    sa.Column('kick_returns_touchdowns', sa.Float(), nullable=True),
    sa.Column('kick_returns_yards', sa.Float(), nullable=True),
    sa.Column('kicking_fg_att', sa.Float(), nullable=True),
    sa.Column('kicking_fg_long', sa.Float(), nullable=True),
    sa.Column('kicking_fg_made', sa.Float(), nullable=True),
    sa.Column('kicking_xk_att', sa.Float(), nullable=True),
    sa.Column('kicking_xk_made', sa.Float(), nullable=True),
    sa.Column('passing_attempts', sa.Float(), nullable=True),
    sa.Column('passing_completions', sa.Float(), nullable=True),
    sa.Column('passing_touchdowns', sa.Float(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('passing_interceptions', sa.Float(), nullable=True),
    sa.Column('punt_returns', sa.Float(), nullable=True),
    sa.Column('punting_average_yards', sa.Float(), nullable=True),
    sa.Column('punting_long', sa.Float(), nullable=True),
    sa.Column('punting_punts', sa.Float(), nullable=True),
    sa.Column('punting_punts_inside20', sa.Float(), nullable=True),
    sa.Column('receiving_receptions', sa.Float(), nullable=True),
    sa.Column('receiving_target', sa.Float(), nullable=True),
    sa.Column('receiving_touchdowns', sa.Float(), nullable=True),
    sa.Column('receiving_yards', sa.Float(), nullable=True),
    sa.Column('rushing_attempts', sa.Float(), nullable=True),
    sa.Column('rushing_average_yards', sa.Float(), nullable=True),
    sa.Column('rushing_touchdowns', sa.Float(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('kickoff_returns_touchdowns', sa.Float(), nullable=True),
    sa.Column('kickoff_returns_yards', sa.Float(), nullable=True),
    sa.Column('punt_returns_long', sa.Float(), nullable=True),
    sa.Column('opponent_fumble_recovery', sa.Float(), nullable=True),
    sa.Column('total_points_scored', sa.Float(), nullable=True),
    sa.Column('kick_returns_average_yards', sa.Float(), nullable=True),
    sa.Column('punt_returns_average_yards', sa.Float(), nullable=True),
    sa.Column('punt_returns_touchdowns', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_game.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'person_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_player_game_stats')
    op.drop_table('nfl_game')
    # ### end Alembic commands ###
