"""empty message

Revision ID: 39af87230883
Revises: f421e25278d0
Create Date: 2018-10-30 21:10:00.907017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39af87230883'
down_revision = 'f421e25278d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shark_projections',
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('scoring', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['field_player.shark_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], ),
    sa.PrimaryKeyConstraint('segment', 'scoring', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shark_projections')
    # ### end Alembic commands ###
