"""empty message

Revision ID: 42fd2e9153a0
Revises: 8d51ec07eee8
Create Date: 2018-10-14 18:16:36.798305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42fd2e9153a0'
down_revision = '8d51ec07eee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfl_boxscore_punt_returns')
    op.drop_table('nfl_boxscore_defense')
    op.drop_table('nfl_boxscore_fumbles')
    op.drop_table('nfl_game')
    op.drop_table('nfl_boxscore_receiving')
    op.drop_table('nfl_boxscore_kickoff_returns')
    op.drop_table('nfl_boxscore_rushing')
    op.drop_table('nfl_boxscore_punting')
    op.drop_table('nfl_boxscore_kicking')
    op.drop_table('nfl_boxscore_passing')
    op.drop_table('nfl_boxscore_game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_boxscore_passing',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('cp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_passing_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_passing_pkey')
    )
    op.create_table('nfl_boxscore_kicking',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('fg_att', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fg_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xp_att', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xp_made', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_kicking_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_kicking_pkey')
    )
    op.create_table('nfl_boxscore_punting',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('i20', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_punting_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_punting_pkey')
    )
    op.create_table('nfl_boxscore_rushing',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('att', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('lg_td', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_rushing_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_rushing_pkey')
    )
    op.create_table('nfl_boxscore_kickoff_returns',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_kickoff_returns_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_kickoff_returns_pkey')
    )
    op.create_table('nfl_boxscore_receiving',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('rec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('lg_td', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_receiving_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_receiving_pkey')
    )
    op.create_table('nfl_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('season_week', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['nfl_team.id'], name='nfl_game_away_team_id_fkey'),
    sa.ForeignKeyConstraint(['home_team_id'], ['nfl_team.id'], name='nfl_game_home_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='nfl_game_pkey')
    )
    op.create_table('nfl_boxscore_fumbles',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('fum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lost', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rec', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_fumbles_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_fumbles_pkey')
    )
    op.create_table('nfl_boxscore_game',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('nfl_boxscore_game_id_seq'::regclass)"), nullable=False),
    sa.Column('home_team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('away_team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('week', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='nfl_boxscore_game_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('nfl_boxscore_defense',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('t', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('a', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sck', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('int', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ff', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_defense_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_defense_pkey')
    )
    op.create_table('nfl_boxscore_punt_returns',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('td', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lg', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('team', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('lg_td', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['nfl_boxscore_game.id'], name='nfl_boxscore_punt_returns_game_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', 'player_id', name='nfl_boxscore_punt_returns_pkey')
    )
    # ### end Alembic commands ###
