"""empty message

Revision ID: 5c1a09488932
Revises: 6dbb8fb1c3ab
Create Date: 2018-10-01 22:10:34.569220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1a09488932'
down_revision = '6dbb8fb1c3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfl_boxscore_rushing', sa.Column('lg_td', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfl_boxscore_rushing', 'lg_td')
    # ### end Alembic commands ###
