"""empty message

Revision ID: 5d6b56b7dc32
Revises: 3dba6cbbd447
Create Date: 2018-10-30 21:00:32.264633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6b56b7dc32'
down_revision = '3dba6cbbd447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_id', sa.Integer(), nullable=True),
    sa.Column('shark_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id'),
    sa.UniqueConstraint('shark_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_player')
    # ### end Alembic commands ###
