"""empty message

Revision ID: 729a6131b19f
Revises: 2236be5f3ade
Create Date: 2018-10-28 11:18:18.668668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '729a6131b19f'
down_revision = '2236be5f3ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_projections',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('positions', postgresql.ARRAY(sa.String(length=8)), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'league_id')
    )
    op.create_table('shark_projections',
    sa.Column('segment', sa.Integer(), nullable=False),
    sa.Column('scoring', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], ),
    sa.PrimaryKeyConstraint('segment', 'scoring', 'player_name', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shark_projections')
    op.drop_table('espn_projections')
    # ### end Alembic commands ###
