"""empty message

Revision ID: 7484fdebd116
Revises: c1162743df1d
Create Date: 2018-10-31 19:23:29.452484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7484fdebd116'
down_revision = 'c1162743df1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'field_team', ['shark_code'])
    op.create_unique_constraint(None, 'field_team', ['espn_id'])
    op.create_unique_constraint(None, 'field_team', ['espn_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_team', type_='unique')
    op.drop_constraint(None, 'field_team', type_='unique')
    op.drop_constraint(None, 'field_team', type_='unique')
    # ### end Alembic commands ###
