"""empty message

Revision ID: 8c0320e3730e
Revises: 2b16e6ef1da2
Create Date: 2018-10-14 20:16:47.642476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0320e3730e'
down_revision = '2b16e6ef1da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('nfl_player_game_stats_game_id_fkey', 'nfl_player_game_stats', type_='foreignkey')
    op.create_foreign_key(None, 'nfl_player_game_stats', 'nfl_game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nfl_player_game_stats', type_='foreignkey')
    op.create_foreign_key('nfl_player_game_stats_game_id_fkey', 'nfl_player_game_stats', 'nfl_game', ['game_id'], ['id'])
    # ### end Alembic commands ###
