"""empty message

Revision ID: 8d51ec07eee8
Revises: 059ba63d4cb5
Create Date: 2018-10-01 22:28:24.268666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d51ec07eee8'
down_revision = '059ba63d4cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfl_boxscore_punt_returns', sa.Column('lg_td', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfl_boxscore_punt_returns', 'lg_td')
    # ### end Alembic commands ###
