"""empty message

Revision ID: c142c9457c1e
Revises: 8bc36e1a8169
Create Date: 2018-10-27 19:36:05.734057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c142c9457c1e'
down_revision = '8bc36e1a8169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=8), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('positions', postgresql.ARRAY(sa.String(length=8)), nullable=True),
    sa.PrimaryKeyConstraint('id', 'league_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espn_projections')
    # ### end Alembic commands ###
