"""empty message

Revision ID: e400dee696f2
Revises: 5d6b56b7dc32
Create Date: 2018-10-30 21:04:00.455078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e400dee696f2'
down_revision = '5d6b56b7dc32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'espn_projections', 'field_player', ['player_id'], ['espn_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'espn_projections', type_='foreignkey')
    # ### end Alembic commands ###
