"""empty message

Revision ID: f421e25278d0
Revises: e400dee696f2
Create Date: 2018-10-30 21:09:12.477823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f421e25278d0'
down_revision = 'e400dee696f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shark_projections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shark_projections',
    sa.Column('segment', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scoring', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('points', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['field_team.id'], name='shark_projections_team_id_fkey'),
    sa.PrimaryKeyConstraint('segment', 'scoring', 'player_name', 'team_id', name='shark_projections_pkey')
    )
    # ### end Alembic commands ###
