"""empty message

Revision ID: fd9dff883afd
Revises: c142c9457c1e
Create Date: 2018-10-27 19:50:45.170054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9dff883afd'
down_revision = 'c142c9457c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espn_projections', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espn_projections', 'status')
    # ### end Alembic commands ###
